// NL manufacturer website roots for brochure/PDF discovery.
// Keyed by canonical brand name from lib/vehicles/brand-registry.json.
// null = no active NL consumer site (legacy-only fleet; brochure discovery skipped).

/** @type {Record<string, string | null>} */
export const MANUFACTURER_WEBSITES = {
  Volkswagen: "https://www.volkswagen.nl",
  Toyota: "https://www.toyota.nl",
  Peugeot: "https://www.peugeot.nl",
  Opel: "https://www.opel.nl",
  Renault: "https://www.renault.nl",
  Ford: "https://www.ford.nl",
  BMW: "https://www.bmw.nl",
  Kia: "https://www.kia.com/nl",
  "Mercedes-Benz": "https://www.mercedes-benz.nl",
  Volvo: "https://www.volvocars.com/nl",
  Audi: "https://www.audi.nl",
  Citroen: "https://www.citroen.nl",
  Hyundai: "https://www.hyundai.nl",
  Fiat: "https://www.fiat.nl",
  Skoda: "https://www.skoda.nl",
  Suzuki: "https://www.suzuki.nl",
  Nissan: "https://www.nissan.nl",
  Seat: "https://www.seat.nl",
  Mazda: "https://www.mazda.nl",
  Mini: "https://www.mini.nl",
  Dacia: "https://www.dacia.nl",
  Tesla: "https://www.tesla.com/nl_NL",
  Cupra: "https://www.cupraofficial.nl",
  "Land Rover": "https://www.landrover.nl",
  Jaguar: "https://www.jaguar.nl",
  Lexus: "https://www.lexus.nl",
  Honda: "https://www.honda.nl",
  Mitsubishi: "https://www.mitsubishi-motors.nl",
  Jeep: "https://www.jeep.nl",
  DS: "https://www.dsautomobiles.nl",
  Smart: "https://www.smart.com/nl",
  "Alfa Romeo": "https://www.alfaromeo.nl",
  Porsche: "https://www.porsche.nl",
  Subaru: "https://www.subaru.nl",
  Polestar: "https://www.polestar.com/nl",
  MG: "https://www.mgmotor.nl",
  BYD: "https://www.byd.com/nl",
  Leapmotor: "https://www.leapmotor.nl",
  Xpeng: "https://www.xpeng.nl",
  Omoda: "https://www.omoda.nl",
  Jaecoo: "https://www.jaecoo.nl",
  Aiways: "https://www.aiways.nl",
  Seres: "https://www.seres.nl",
  "Lynk & Co": "https://www.lynkco.com/nl",
  Genesis: "https://www.genesis.com/nl",
  Ineos: "https://www.ineosgrenadier.com/nl",
  Alpine: "https://www.alpinecars.com/nl",
  Lotus: "https://www.lotuscars.com/nl",
  Maserati: "https://www.maserati.com/nl",
  Bentley: "https://www.bentleymotors.com/nl",
  "Rolls-Royce": "https://www.rolls-roycemotorcars.com/nl",
  "Aston Martin": "https://www.astonmartin.com/nl",
  Ferrari: "https://www.ferrari.com/nl-NL",
  Lamborghini: "https://www.lamborghini.com/nl-en",
  McLaren: "https://www.mclaren.com/nl",
  Abarth: "https://www.abarth.nl",
  Chrysler: "https://www.chrysler.com",
  Dodge: "https://www.dodge.com",
  Cadillac: "https://www.cadillac.com",
  Chevrolet: "https://www.chevrolet.com",
  Lincoln: "https://www.lincoln.com",
  Nio: "https://www.nio.com/nl",
  Zeekr: "https://www.zeekr.eu/nl",
  VinFast: "https://www.vinfastauto.nl",
  Rivian: "https://rivian.com/nl",
  Lucid: "https://www.lucidmotors.com/nl-nl",
  Hongqi: "https://www.hongqi-auto.com",
  Maxus: "https://www.maxus.nl",
  DFSK: "https://www.dfsk.nl",
  "Great Wall": "https://www.gwm-eu.com/nl",
  Haval: "https://www.haval.nl",
  Chery: "https://www.chery.nl",
  Geely: "https://www.geely.nl",
  Ora: "https://www.ora.eu/nl",
  GWM: "https://www.gwm-eu.com/nl",
  Foton: null,
  JAC: "https://www.jac.nl",
  BAIC: "https://www.baic.nl",
  SsangYong: "https://www.kg-mobility.eu/nl",
  KGM: "https://www.kg-mobility.eu/nl",
  Alpina: "https://www.alpina-automobiles.com",
  Lancia: "https://www.lancia.com",
  Daihatsu: null,
  Saab: null,
  Rover: null,
  Triumph: null,
  Daewoo: null,
  Pontiac: null,
  Austin: null,
  DAF: null,
  Datsun: null,
  Oldsmobile: null,
  Lada: null,
  Trabant: null,
  Infiniti: null,
  Morgan: "https://www.morgan-motor.com",
  Donkervoort: "https://www.donkervoort.com",
  TVR: null,
  Fisker: null,
};

/** Custom brochure adapters that override or extend generic discovery. */
export const BRAND_ADAPTERS = {
  hyundai: "hyundai",
};

export const DOCUMENT_KEYWORDS = [
  "prijslijst",
  "prijzenlijst",
  "brochure",
  "specificaties",
  "technisch",
  "technische",
  "equipment",
  "uitrusting",
  "prijzen",
  "price-list",
  "pricelist",
];

export const MODEL_PATH_TEMPLATES = [
  "/modellen/{model}",
  "/models/{model}",
  "/model/{model}",
  "/auto/{model}",
  "/personenwagens/{model}",
  "/nieuwe-modellen/{model}",
  "/modellen/{model}/",
  "/models/{model}/",
];
