// Curated passenger-car brands that are discontinued, exited NL, or niche/legacy.
// RDW merk spellings are merged under canonical names so plate lookup stays predictable.
// Regenerate counts with: npm run generate:brand-registry

/** @type {Array<{ canonical: string, rdwMerken: string[], marketStatus: string, notes?: string }>} */
export const LEGACY_RARE_BRANDS = [
  { canonical: "Saab", rdwMerken: ["SAAB"], marketStatus: "discontinued", notes: "Production ended 2012" },
  { canonical: "Lancia", rdwMerken: ["LANCIA"], marketStatus: "discontinued", notes: "No new passenger cars in NL" },
  { canonical: "Rover", rdwMerken: ["ROVER"], marketStatus: "discontinued" },
  { canonical: "Austin", rdwMerken: ["AUSTIN"], marketStatus: "discontinued" },
  { canonical: "Morris", rdwMerken: ["MORRIS"], marketStatus: "discontinued" },
  { canonical: "Riley", rdwMerken: ["RILEY"], marketStatus: "discontinued" },
  { canonical: "Wolseley", rdwMerken: ["WOLSELEY"], marketStatus: "discontinued" },
  { canonical: "Hillman", rdwMerken: ["HILLMAN"], marketStatus: "discontinued" },
  { canonical: "Sunbeam", rdwMerken: ["SUNBEAM"], marketStatus: "discontinued" },
  { canonical: "Talbot", rdwMerken: ["TALBOT"], marketStatus: "discontinued" },
  { canonical: "Simca", rdwMerken: ["SIMCA"], marketStatus: "discontinued" },
  { canonical: "Triumph", rdwMerken: ["TRIUMPH"], marketStatus: "discontinued" },
  { canonical: "Austin-Healey", rdwMerken: ["AUSTIN-HEALEY", "AUSTIN HEALEY"], marketStatus: "discontinued" },
  { canonical: "Jensen", rdwMerken: ["JENSEN"], marketStatus: "discontinued" },
  { canonical: "Reliant", rdwMerken: ["RELIANT"], marketStatus: "discontinued" },
  { canonical: "Bond", rdwMerken: ["BOND"], marketStatus: "discontinued" },
  { canonical: "Standard", rdwMerken: ["STANDARD"], marketStatus: "discontinued" },
  { canonical: "Singer", rdwMerken: ["SINGER"], marketStatus: "discontinued" },
  { canonical: "Vanden Plas", rdwMerken: ["VANDEN PLAS"], marketStatus: "discontinued" },
  { canonical: "Alvis", rdwMerken: ["ALVIS"], marketStatus: "discontinued" },
  { canonical: "Armstrong Siddeley", rdwMerken: ["ARMSTRONG SIDDELEY"], marketStatus: "discontinued" },
  { canonical: "Lagonda", rdwMerken: ["LAGONDA"], marketStatus: "discontinued" },
  { canonical: "Marcos", rdwMerken: ["MARCOS"], marketStatus: "discontinued" },
  { canonical: "TVR", rdwMerken: ["TVR"], marketStatus: "discontinued" },
  { canonical: "Noble", rdwMerken: ["NOBLE"], marketStatus: "discontinued" },
  { canonical: "Caterham", rdwMerken: ["CATERHAM"], marketStatus: "niche" },
  { canonical: "Westfield", rdwMerken: ["WESTFIELD"], marketStatus: "niche" },
  { canonical: "Morgan", rdwMerken: ["MORGAN"], marketStatus: "niche" },
  { canonical: "Donkervoort", rdwMerken: ["DONKERVOORT"], marketStatus: "niche" },
  { canonical: "Spyker", rdwMerken: ["SPYKER"], marketStatus: "discontinued" },
  { canonical: "Bitter", rdwMerken: ["BITTER"], marketStatus: "discontinued" },
  { canonical: "Borgward", rdwMerken: ["BORGWARD"], marketStatus: "discontinued" },
  { canonical: "NSU", rdwMerken: ["NSU", "N.S.U."], marketStatus: "discontinued" },
  { canonical: "Auto Union", rdwMerken: ["AUTO UNION"], marketStatus: "discontinued" },
  { canonical: "DKW", rdwMerken: ["DKW"], marketStatus: "discontinued" },
  { canonical: "Glas", rdwMerken: ["GLAS"], marketStatus: "discontinued" },
  { canonical: "Horch", rdwMerken: ["HORCH"], marketStatus: "discontinued" },
  { canonical: "Wanderer", rdwMerken: ["WANDERER"], marketStatus: "discontinued" },
  { canonical: "Trabant", rdwMerken: ["TRABANT"], marketStatus: "discontinued" },
  { canonical: "Wartburg", rdwMerken: ["WARTBURG"], marketStatus: "discontinued" },
  { canonical: "Lada", rdwMerken: ["LADA"], marketStatus: "discontinued" },
  { canonical: "Zastava", rdwMerken: ["ZASTAVA"], marketStatus: "discontinued" },
  { canonical: "Yugo", rdwMerken: ["YUGO"], marketStatus: "discontinued" },
  { canonical: "FSO", rdwMerken: ["FSO"], marketStatus: "discontinued" },
  { canonical: "Polski Fiat", rdwMerken: ["POLSKI FIAT"], marketStatus: "discontinued" },
  { canonical: "Moskvitch", rdwMerken: ["MOSKVITCH", "MOSKOVITCH"], marketStatus: "discontinued" },
  { canonical: "Innocenti", rdwMerken: ["INNOCENTI"], marketStatus: "discontinued" },
  { canonical: "Autobianchi", rdwMerken: ["AUTO BIANCHI", "AUTOBIANCHI"], marketStatus: "discontinued" },
  { canonical: "Iso", rdwMerken: ["ISO"], marketStatus: "discontinued" },
  { canonical: "De Tomaso", rdwMerken: ["DE TOMASO", "DE-TOMASO"], marketStatus: "discontinued" },
  { canonical: "Matra", rdwMerken: ["MATRA"], marketStatus: "discontinued" },
  { canonical: "Alpine-Renault", rdwMerken: ["ALPINE-RENAULT"], marketStatus: "discontinued" },
  { canonical: "DAF", rdwMerken: ["DAF"], marketStatus: "discontinued", notes: "Passenger cars ended 1970s; trucks remain separate" },
  { canonical: "Pontiac", rdwMerken: ["PONTIAC"], marketStatus: "discontinued" },
  { canonical: "Oldsmobile", rdwMerken: ["OLDSMOBILE"], marketStatus: "discontinued" },
  { canonical: "Plymouth", rdwMerken: ["PLYMOUTH"], marketStatus: "discontinued" },
  { canonical: "Mercury", rdwMerken: ["MERCURY"], marketStatus: "discontinued" },
  { canonical: "Saturn", rdwMerken: ["SATURN"], marketStatus: "discontinued" },
  { canonical: "Hummer", rdwMerken: ["HUMMER"], marketStatus: "discontinued" },
  { canonical: "Scion", rdwMerken: ["SCION"], marketStatus: "discontinued" },
  { canonical: "Eagle", rdwMerken: ["EAGLE"], marketStatus: "discontinued" },
  { canonical: "Geo", rdwMerken: ["GEO"], marketStatus: "discontinued" },
  { canonical: "AMC", rdwMerken: ["AMC", "AMERICAN MOTORS"], marketStatus: "discontinued" },
  { canonical: "Rambler", rdwMerken: ["RAMBLER"], marketStatus: "discontinued" },
  { canonical: "Studebaker", rdwMerken: ["STUDEBAKER"], marketStatus: "discontinued" },
  { canonical: "Packard", rdwMerken: ["PACKARD"], marketStatus: "discontinued" },
  { canonical: "Hudson", rdwMerken: ["HUDSON"], marketStatus: "discontinued" },
  { canonical: "Nash", rdwMerken: ["NASH"], marketStatus: "discontinued" },
  { canonical: "Kaiser", rdwMerken: ["KAISER"], marketStatus: "discontinued" },
  { canonical: "Willys", rdwMerken: ["WILLYS"], marketStatus: "discontinued" },
  { canonical: "DeSoto", rdwMerken: ["DESOTO", "DE SOTO"], marketStatus: "discontinued" },
  { canonical: "Edsel", rdwMerken: ["EDSEL"], marketStatus: "discontinued" },
  { canonical: "DeLorean", rdwMerken: ["DELOREAN", "DE LOREAN"], marketStatus: "discontinued" },
  { canonical: "Datsun", rdwMerken: ["DATSUN"], marketStatus: "discontinued", notes: "Revived as sub-brand; RDW still lists historic Datsun" },
  { canonical: "Daewoo", rdwMerken: ["DAEWOO"], marketStatus: "discontinued" },
  { canonical: "SsangYong", rdwMerken: ["SSANGYONG", "SSANG YONG"], marketStatus: "discontinued", notes: "KGM rebrand; historic RDW rows remain" },
  { canonical: "Proton", rdwMerken: ["PROTON"], marketStatus: "discontinued" },
  { canonical: "Perodua", rdwMerken: ["PERODUA"], marketStatus: "discontinued" },
  { canonical: "Daihatsu", rdwMerken: ["DAIHATSU"], marketStatus: "exited_nl" },
  { canonical: "Isuzu", rdwMerken: ["ISUZU"], marketStatus: "exited_nl", notes: "Passenger cars largely exited; pickups remain" },
  { canonical: "Infiniti", rdwMerken: ["INFINITI"], marketStatus: "exited_eu" },
  { canonical: "Holden", rdwMerken: ["HOLDEN"], marketStatus: "discontinued" },
  { canonical: "Vauxhall", rdwMerken: ["VAUXHALL"], marketStatus: "discontinued", notes: "UK brand; distinct RDW merk from Opel imports" },
  { canonical: "Bedford", rdwMerken: ["BEDFORD"], marketStatus: "discontinued" },
  { canonical: "Daimler", rdwMerken: ["DAIMLER"], marketStatus: "discontinued", notes: "Historic British marque, not Mercedes parent" },
  { canonical: "Rover Group", rdwMerken: ["ROVER GROUP"], marketStatus: "discontinued" },
  { canonical: "Austin Rover", rdwMerken: ["AUSTIN ROVER"], marketStatus: "discontinued" },
  { canonical: "Fisker", rdwMerken: ["FISKER"], marketStatus: "discontinued" },
  { canonical: "Vector", rdwMerken: ["VECTOR"], marketStatus: "discontinued" },
  { canonical: "Saleen", rdwMerken: ["SALEEN"], marketStatus: "niche" },
  { canonical: "Panoz", rdwMerken: ["PANOZ"], marketStatus: "niche" },
  { canonical: "Wiesmann", rdwMerken: ["WIESMANN"], marketStatus: "niche" },
  { canonical: "Ginetta", rdwMerken: ["GINETTA"], marketStatus: "niche" },
  { canonical: "Ariel", rdwMerken: ["ARIEL"], marketStatus: "niche" },
  { canonical: "BAC", rdwMerken: ["BAC"], marketStatus: "niche" },
  { canonical: "Radical", rdwMerken: ["RADICAL"], marketStatus: "niche" },
  { canonical: "Zenos", rdwMerken: ["ZENOS"], marketStatus: "discontinued" },
  { canonical: "Invicta", rdwMerken: ["INVICTA"], marketStatus: "discontinued" },
  { canonical: "Bristol", rdwMerken: ["BRISTOL"], marketStatus: "discontinued" },
  { canonical: "Panhard", rdwMerken: ["PANHARD"], marketStatus: "discontinued" },
  { canonical: "Facel Vega", rdwMerken: ["FACEL", "FACEL VEGA"], marketStatus: "discontinued" },
  { canonical: "Monteverdi", rdwMerken: ["MONTEVERDI"], marketStatus: "discontinued" },
  { canonical: "Stutz", rdwMerken: ["STUTZ"], marketStatus: "discontinued" },
  { canonical: "Excalibur", rdwMerken: ["EXCALIBUR"], marketStatus: "discontinued" },
  { canonical: "Checker", rdwMerken: ["CHECKER"], marketStatus: "discontinued" },
  { canonical: "Cord", rdwMerken: ["CORD"], marketStatus: "discontinued" },
  { canonical: "Duesenberg", rdwMerken: ["DUESENBERG"], marketStatus: "discontinued" },
  { canonical: "Franklin", rdwMerken: ["FRANKLIN"], marketStatus: "discontinued" },
  { canonical: "Pierce-Arrow", rdwMerken: ["PIERCE ARROW", "PIERCE-ARROW"], marketStatus: "discontinued" },
  { canonical: "Tatra", rdwMerken: ["TATRA"], marketStatus: "discontinued" },
];

/** RDW merk values that are aliases of active brands, not separate marques. */
export const ACTIVE_BRAND_ALIASES = {
  Volkswagen: ["VW", "VW-PORSCHE", "VOLKSWAGEN AG"],
  Audi: ["AUDI-NSU", "AUDI/PORSCHE", "QUATTRO"],
  BMW: ["BMW I", "BMW/ALPINA", "BMW-GLAS"],
  "Mercedes-Benz": ["MERCEDES-AMG", "DAIMLER BENZ", "DAIMLERCHRYSLER AG", "MERCEDES BENZ"],
  Jaguar: ["JAGUAR CARS", "JAGUAR LAND ROVER"],
  "Land Rover": ["LANDROVER"],
  Tesla: ["TESLA MOTORS"],
  DS: ["DS AUTOMOBILES"],
  Smart: ["MICRO COMPACT CAR SMART", "MCC SMART"],
  "Rolls-Royce": ["ROLLS ROYCE"],
  Lamborghini: ["AUTOMOBILI LAMBORGHINI S.", "LAMBORGHINI"],
  Mini: ["MINI COOPER"],
  Citroen: ["CITROËN"],
  "Lynk & Co": ["LYNK&CO", "LYNK & CO"],
  Skoda: ["SKODA AUTO"],
  MG: ["MG"],
  Alpina: ["ALPINA"],
};

/** Currently sold or common passenger-car brands in NL (for tier separation). */
export const ACTIVE_BRANDS = [
  "Volkswagen", "Toyota", "Peugeot", "Opel", "Renault", "Ford", "BMW", "Kia",
  "Mercedes-Benz", "Volvo", "Audi", "Citroen", "Hyundai", "Fiat", "Skoda", "Suzuki",
  "Nissan", "Seat", "Mazda", "Mini", "Dacia", "Tesla", "Cupra", "Land Rover",
  "Jaguar", "Lexus", "Honda", "Mitsubishi", "Jeep", "DS", "Smart", "Alfa Romeo",
  "Porsche", "Subaru", "Polestar", "MG", "BYD", "Leapmotor", "Xpeng", "Omoda",
  "Jaecoo", "Aiways", "Seres", "Lynk & Co", "Genesis", "Ineos", "Alpine", "Lotus",
  "Maserati", "Bentley", "Rolls-Royce", "Aston Martin", "Ferrari", "Lamborghini",
  "McLaren", "Abarth", "Chrysler", "Dodge", "Cadillac", "Chevrolet", "Lincoln",
  "Nio", "Zeekr", "VinFast", "Rivian", "Lucid", "Hongqi", "Maxus", "DFSK",
  "Great Wall", "Haval", "Chery", "Geely", "Ora", "GWM", "Foton", "JAC", "BAIC",
  "SsangYong", "KGM",
];

/** Exclude camper, trailer, chassis, and conversion noise from auto-detection. */
export const NON_PASSENGER_MERK_PATTERN =
  /TRAILER|CAMPER|CARAVAN|CHASSIS|AANHANG|OPBOUW|KIP\b|KNOTT|AL-KO|ALKO|BPW|JOKER|SCHMITZ|KNAUS|HOBBY|FENDT|BURSTNER|BÜRSTNER|BUERSTNER|ADRIA\b|LMC\b|DETHLEFFS|ERIBA|HYMER|KARMANN|WESTFALIA|REIMO|TEC\b|ROLLER|TEAM\b|TABBERT|LUNAR\b|SWIFT\b|BAILEY|ELDDIS|COACHMAN|THULE|NIEUWKAMP|CAPRON|CHAUSSON|CARTHAGO|WEINSBERG|RAPIDO|MC LOUIS|BENIMAR|EURA MOBIL|PILOTE|TRIGANO|SUN LIVING|ELNAGH|RIMOR|MOBILVETTA|LAIKA|ETRUSCO|FRANKIA|GIOTTILINE|JOINT|POESSL|POSSL|NEKAF|NIESMANN|FRANKIA|KABE|HOBBY\b|DETHLEFFS|BURSTNER/i;
